services:
    web:
        image: nginx
        ports:
            - 8082:80
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        networks:
            - app-network

    php-fpm:
        build: docker/php
        volumes:
            - .:/var/www/html
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        networks:
            - app-network

    postgres:
        image: postgres:13
        volumes:
            - ./docker/postgres/data:/var/lib/postgresql/data
        ports:
            - 54323:5432
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        networks:
            - app-network

    rabbitmq:
        image: rabbitmq:3-management
        hostname: rabbitmq
        restart: always
        command: >
            /bin/bash -c "
              chmod 600 /var/lib/rabbitmq/.erlang.cookie &&
              rabbitmq-server"
        environment:
            - RABBITMQ_DEFAULT_USER=rmuser
            - RABBITMQ_DEFAULT_PASS=rmpassword
            - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 104857600
        volumes:
            - ./rabbitmq:/var/lib/rabbitmq
        ports:
            - 15672:15672
            - 5672:5672
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - "63791:6379"
        #volumes:
        #    - redis_data:/data
        restart: unless-stopped
        networks:
            - app-network

volumes:
    redis_data:
        driver: local

networks:
    app-network:
        driver: bridge
